apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-service
  namespace: skishop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-service
  template:
    metadata:
      labels:
        app: point-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: skishop-sa
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: skishop-secrets
      containers:
      - name: point-service
        image: <ACR_LOGIN_SERVER>/point-service:latest
        ports:
        - containerPort: 8085
        volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: skishop-secrets
              key: POINT_DB_URL
        - name: DB_USERNAME
          value: "<DB_ADMIN_USER>"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skishop-secrets
              key: DB_ADMIN_PASS
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: skishop-secrets
              key: JWT_SECRET
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: skishop-secrets
              key: INTERNAL_API_KEY
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: skishop-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: skishop-config
              key: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
        - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
          valueFrom:
            configMapKeyRef:
              name: skishop-config
              key: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
        - name: EVENTHUB_CS
          valueFrom:
            secretKeyRef:
              name: skishop-secrets
              key: EVENTHUB_CS
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: skishop-config
              key: SPRING_PROFILES_ACTIVE
        resources:
          requests:
            memory: "384Mi"
            cpu: "100m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 180
          periodSeconds: 20
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: point-service
  namespace: skishop
spec:
  selector:
    app: point-service
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP
