# Dev profile
spring.datasource.url=jdbc:postgresql://localhost:5432/skishop_auth
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

logging.level.root=INFO
logging.level.com.example.skishop=DEBUG
logging.level.org.springframework.web=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus,env
management.endpoint.health.show-details=always

server.error.include-message=always
