apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: skishop-secrets
  namespace: skishop
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "<WORKLOAD_IDENTITY_CLIENT_ID>"
    keyvaultName: "skishop-kv"
    cloudName: "AzurePublicCloud"
    tenantId: "<AZURE_TENANT_ID>"
    objects: |
      array:
        - |
          objectName: DB-ADMIN-PASS
          objectType: secret
          objectAlias: DB_ADMIN_PASS
        - |
          objectName: DB-ADMIN-USER
          objectType: secret
          objectAlias: DB_ADMIN_USER
        - |
          objectName: JWT-SECRET
          objectType: secret
          objectAlias: JWT_SECRET
        - |
          objectName: INTERNAL-API-KEY
          objectType: secret
          objectAlias: INTERNAL_API_KEY
        - |
          objectName: NEXTAUTH-SECRET
          objectType: secret
          objectAlias: NEXTAUTH_SECRET
        - |
          objectName: EVENTHUB-CS
          objectType: secret
          objectAlias: EVENTHUB_CS
        - |
          objectName: AUTH-DB-URL
          objectType: secret
          objectAlias: AUTH_DB_URL
        - |
          objectName: USER-DB-URL
          objectType: secret
          objectAlias: USER_DB_URL
        - |
          objectName: SALES-DB-URL
          objectType: secret
          objectAlias: SALES_DB_URL
        - |
          objectName: PAYMENT-DB-URL
          objectType: secret
          objectAlias: PAYMENT_DB_URL
        - |
          objectName: POINT-DB-URL
          objectType: secret
          objectAlias: POINT_DB_URL
        - |
          objectName: COUPON-DB-URL
          objectType: secret
          objectAlias: COUPON_DB_URL
        - |
          objectName: MAIL-DB-URL
          objectType: secret
          objectAlias: MAIL_DB_URL
        - |
          objectName: COSMOS-CS
          objectType: secret
          objectAlias: COSMOS_CS
        - |
          objectName: ACR-PASSWORD
          objectType: secret
          objectAlias: ACR_PASSWORD
        - |
          objectName: ACS-CONNECTION-STRING
          objectType: secret
          objectAlias: ACS_CONNECTION_STRING
        - |
          objectName: MAIL-SENDER-ADDRESS
          objectType: secret
          objectAlias: MAIL_SENDER_ADDRESS
  secretObjects:
  - secretName: skishop-secrets
    type: Opaque
    data:
    - objectName: DB_ADMIN_PASS
      key: DB_ADMIN_PASS
    - objectName: DB_ADMIN_USER
      key: DB_ADMIN_USER
    - objectName: JWT_SECRET
      key: JWT_SECRET
    - objectName: INTERNAL_API_KEY
      key: INTERNAL_API_KEY
    - objectName: NEXTAUTH_SECRET
      key: NEXTAUTH_SECRET
    - objectName: EVENTHUB_CS
      key: EVENTHUB_CS
    - objectName: AUTH_DB_URL
      key: AUTH_DB_URL
    - objectName: USER_DB_URL
      key: USER_DB_URL
    - objectName: SALES_DB_URL
      key: SALES_DB_URL
    - objectName: PAYMENT_DB_URL
      key: PAYMENT_DB_URL
    - objectName: POINT_DB_URL
      key: POINT_DB_URL
    - objectName: COUPON_DB_URL
      key: COUPON_DB_URL
    - objectName: MAIL_DB_URL
      key: MAIL_DB_URL
    - objectName: COSMOS_CS
      key: COSMOS_CS
    - objectName: ACR_PASSWORD
      key: ACR_PASSWORD
    - objectName: ACS_CONNECTION_STRING
      key: ACS_CONNECTION_STRING
    - objectName: MAIL_SENDER_ADDRESS
      key: MAIL_SENDER_ADDRESS
